import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const barlow = Barlow({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <div className="bg-black min-h-screen">
          <NavBar />
          <>{children}</>
          <Footer />
        </div>
      </body>
    </html>
  );
}
